# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvp" do
  version "2.2.0"

  on_macos do
    on_arm do
      sha256 "0a7258c216897e31256f84f2eaa940afe2364493dd94469977e15681c535d0ca"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "266609e0cd0c0404616129a75f1ea7a230ffdc4bdd8f25adbcf7043b7e53066c"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "34083dbf0dff73298a684ba48f9f945e6d0362d203e1bd87cbe5e797498b6551"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77e039e34b956d833334eb167f193e2c7a0a772219dfc492e886c31b0a6f7c10"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Linux_x86_64.tar.gz"
    end
  end

  name "rvp"
  desc "A noise-reduction engine for Trivy scans using EPSS and VEX."
  homepage "https://github.com/ConnorHampstead/reasonable-vulnerability-processor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvp"]
    end
  end

  # No zap stanza required
end
