# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvp" do
  version "3.0.0"

  on_macos do
    on_arm do
      sha256 "e21f0d5b4112917d73a2f5d02900ea4d11de7f1987fe21650584b2dda561fc7c"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "804e7cc818bf8099c6416aec55c41e0e1907bfc01a906f541601eab48395f69d"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "caf1fa579532f170938ff8c3a10fcfe9005a96201f57c2ff3a6edbd0442488a5"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e60c14c2baede1c7474a8c7d400eb45e5d62555f3f07413e19c70f4258e9bd2f"
      url "https://github.com/ConnorHampstead/reasonable-vulnerability-processor/releases/download/v#{version}/rvp_Linux_x86_64.tar.gz"
    end
  end

  name "rvp"
  desc "A noise-reduction engine for Trivy scans using EPSS and VEX."
  homepage "https://github.com/ConnorHampstead/reasonable-vulnerability-processor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvp"]
    end
  end

  # No zap stanza required
end
